### ISSUE TITLE
Feature request - add digits argument to CAGR

### ISSUE THREAD

**Issue by ellisp** [nz-mbie/mbie-r-package#3]
Currently CAGR rounds to one digit and can't be over-ridden.  Can you add a digits argument which defaults to one but can be changed

```R
function (ratio, period, digits = 1) 
{
    round((exp(log(ratio)/period) - 1) * 100, digits)
}
```

**Comment by PeteMcM** [comment]
Done. Currently with @HaizhenWu for peer review.
