### ISSUE TITLE
animation_frames broken with facetted plots

### ISSUE THREAD

**Issue by ellisp** [nz-mbie/mbie-r-package#5]
I didn't have time to fully check but in preparing a presentation in a rush yesterday I couldn't get animation_frames working with facetted plots; including the example in the helpfiles.  In the end I made my animations 'by hand' ie with explicit loops etc.

Someone needs to check to see if this is a general problem and if so fix it (I'm confident it will be fixable).

**Comment by havukkala** [comment]
Hi Peter

I got this to work by adding to end of data file creation pipeline %>% as.data.frame


# Example 3 - more complex time series
library(Cairo)
library(dplyr)
library(mbiedata)
data(IVStrips)

tmp <- IVStrips %>%
   group_by(YEJun, POVTop3, COPRTop5) %>%
   summarise(Spend = sum(FinalWeight * SmoothTotalSpend * Adjusted_Factor)) %>% as.data.frame

plot3 <- ggplot(tmp, aes(x = YEJun, y = Spend / 10 ^ 6, colour = COPRTop5)) +
   facet_wrap( ~ POVTop3) +
   geom_line() +
   scale_colour_manual(values = tourism.cols()) +
   scale_y_continuous("Total tourist spend ($m)\n", label = comma, limits = c(0, 1.7 * 10 ^ 3)) +
   scale_x_continuous("", limits = c(1997, 2014)) +
   theme_bw(base_family = "Calibri")

animation_frames(plot3, filename = "IVS", width = 9, height = 7)



Ilkka Havukkala
RESEARCH ANALYST

Sector Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment


Ilkka.havukkala@mbie.govt.nz<mailto:Ilkka.havukkala@mbie.govt.nz>  Telephone: +64 4 901 1516
Level 7, 15 Stout St, Welllington, 6011 | PO Box 3705, Wellington, 6140

**Comment by ellisp** [comment]
ok, %>% ungroup() is probably better.  Eric can you fix the example at some point.

**Comment by HaizhenWu** [comment]
%>% ungroup() doesn't work. Suspect it is not issue of grouping. 

```r
> animation_frames(plot3, filename = "IVS", width = 9, height = 7)
Error in `$<-.data.frame`(`*tmp*`, "SCALE_X", value = 1L) : 
  replacement has 1 row, data has 0
In addition: Warning message:
In max(panels$ROW) : no non-missing arguments to max; returning -Inf
```
I have changed to 
```r
tmp <- IVStrips %>%
   group_by(YEJun, POVTop3, COPRTop5) %>%
   summarise(Spend = sum(FinalWeight * SmoothTotalSpend * Adjusted_Factor)) %>%
   data.frame
```
which is equivalent to "as.data.frame".

I also changed the package version to 0.9.2 and updated the NEWS. 

The changes has been made and pushed to repo, but maybe we don't want to deploy this version right now, since this is only a trivial update.

**Comment by ellisp** [comment]
Yes, let's wait till we've got some more things to roll out before we deploy it as 0.9.2 (leave it numbered as such in the description, so if we use it in test we know it is different to the deployed 0.9.1).

Surprising.  I wonder what it is that works with data.frame.  No matter though.
